{% set version = "1.3.10" %}

package:
  name: mkl_fft
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_fft/archive/v{{ version }}.tar.gz
  sha256: c519e7baeb609211d1940c5f69e7f6779895fe143f9476282a3dbb2032dd56ad

build:
  number: 1
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - mkl-devel
    - cython
    - numpy
  run:
    - python
    - mkl
    - mkl-service

test:
  commands:
    - pytest -v --pyargs mkl_fft
  requires:
    - pytest
  imports:
    - mkl_fft
    - mkl_fft.interfaces

about:
  home: http://github.com/IntelPython/mkl_fft
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision with arbitrary memory layout, so long as array strides are multiples of its itemsize.
  summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
