{% set version = "1.0.11" %}
{% set buildnumber = 0 %}

package:
    name: mkl_fft
    version: {{ version }}

source:
    url: https://github.com/IntelPython/mkl_fft/archive/v{{version}}.tar.gz
    sha256: d9adb3befdc57e49ddd4f2716c3fc2661a61a3acd4f6e44809cd642444709dac

build:
    number: {{ buildnumber }}

requirements:
    build:
      - {{ compiler('c') }}
    host:
      - libblas
      - libcblas
      - python
      - setuptools
      - cython
      - numpy 1.11.*
    run:
      - python
      - {{ pin_compatible('numpy') }}

test:
    commands:
      - nosetests -v mkl_fft
    requires:
      - nose
    imports:

about:
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    description:
        NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.
        Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision
        with arbitrary memory layout, so long as array strides are multiples of its itemsize.
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.

extra:
  recipe-maintainers:
     - oleksandr-pavlyk
