{% set version = "1.2.0" %}
{% set buildnumber = 1 %}

package:
  name: mkl_fft
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_fft/archive/v{{ version }}.tar.gz
  sha256: ab34e4a3f3aaa983260b528ec8d7f2b98fcbfebd23c1462315e2efdb92395767

build:
  number: {{ buildnumber }}
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - mkl-devel
    - cython
    - numpy
  run:
    - python
    - mkl
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - nosetests -v mkl_fft
  requires:
    - nose
  imports:
    - mkl_fft
    - mkl_fft._numpy_fft
    - mkl_fft._scipy_fft

about:
  home: http://github.com/IntelPython/mkl_fft
  license: BSD 3-Clause
  license_file: LICENSE.txt
  description: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision with arbitrary memory layout, so long as array strides are multiples of its itemsize.
  summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
