{% set version = "2.0.0" %}

package:
  name: mkl_fft
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_fft/archive/v{{ version }}.tar.gz
  sha256: 539f4a3828e57df2f7b31eb06fddaa64a7d8de469afe10caa14365aeb62f0dad

build:
  number: 2
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=77
    - mkl-devel
    - cython
    - numpy
  run:
    - python
    - numpy
    - mkl-service

test:
  commands:
    - pytest -v --pyargs mkl_fft
  requires:
    - pytest
    - scipy >=1.10
  imports:
    - mkl_fft
    - mkl_fft.interfaces
    - mkl_fft.interfaces.numpy_fft
    - mkl_fft.interfaces.scipy_fft

about:
  home: http://github.com/IntelPython/mkl_fft
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision with arbitrary memory layout, so long as array strides are multiples of its itemsize.
  summary: NumPy-based implementation of Fast Fourier Transform using Intel® oneAPI Math Kernel Library (OneMKL)

extra:
  recipe-maintainers:
    - ekomarova
    - vtavana
    - xaleryb
    - jharlow-intel
