appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: izAPiQIaWG2SY4j4oRPnFIzKfiIVOb58vGZkTs3Gb+lKuchO4f67ptkGtP+0KjHbBApmPWeDYZpj5+kViAq4snfwr/vHKMh20lBrQYAmEDCzrC4M/P/YLbYbYRa+wRJkTc0AtIqsJM56H55SrBJWZhnlmuUlzqWJSE4CrgZBduO16s+UJ8Z1HCGSunac4nSSzvPSXQeoSGtxFkfPlu1/F9CU3AG6JYH7qew1lofqsyeFZbgEkOn6uNGCICeDQZGN4ee0so/8Ta7clRqGBC50A1mrHDeR77/pL2k3KdDNZMRxjXY33BDKQwT/pUhf4g8QPQadrL3phNXYYakMlM24AGzBAMidt9s2KaE8aEEGxbh+iC3h5iF9rEO1ycvDMC9JRzQfZw8LWrbL+urk5o46X9yFH+2J5QWVPHNShHn42DxEpn2yMvqQ8y1jja+ztRvQ+jB0vv3+dq1iMSNn2FVJoMWIXY6Vf+eDR3/OmCKmfROFWI9E1/izyNKpCFl2U+fTSwLckH4LhDlDtTFuCLLiNJ7TmAKWZKxMD0K+u7vRtjJv9QaHoZ2gChEV48Q9Cm2EthqB6+kqS81756J86JofTIUeWWOHSQ37RqkK1QyPI4ig+PcGccgqZ0Am8k0HA9N9Y33ReTw91xveaJ/pmAnZqijbt9HJ/zpHkQ/nbHpjQFA=}
